apiVersion: apps/v1
kind: Deployment
metadata:
  name: deliveryFood
  labels:
    app: deliveryFood
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deliveryFood
  template:
    metadata:
      labels:
        app: deliveryFood
    spec:
      containers:
        - name: deliveryFood
          image: username/deliveryFood:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5