---
  apiVersion: "apps/v1"
  kind: "Deployment"
  metadata: 
    name: "front"
    labels: 
      app: "front"
  spec: 
    selector: 
      matchLabels: 
        app: "front"
    replicas: 1
    template: 
      metadata: 
        labels: 
          app: "front"
      spec: 
        containers: 
          - 
            name: "front"
            image: "front"
            ports: 
              - 
                containerPort: 8080
            readinessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 10
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 10
            livenessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 120
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 5
---
  apiVersion: "v1"
  kind: "Service"
  metadata: 
    name: "front"
    labels: 
      app: "front"
  spec: 
    ports: 
      - 
        port: 8080
        targetPort: 8080
    selector: 
      app: "front"
---
  apiVersion: "apps/v1"
  kind: "Deployment"
  metadata: 
    name: "shop"
    labels: 
      app: "shop"
  spec: 
    selector: 
      matchLabels: 
        app: "shop"
    replicas: 1
    template: 
      metadata: 
        labels: 
          app: "shop"
      spec: 
        containers: 
          - 
            name: "shop"
            image: "shop"
            ports: 
              - 
                containerPort: 8080
            readinessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 10
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 10
            livenessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 120
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 5
---
  apiVersion: "v1"
  kind: "Service"
  metadata: 
    name: "shop"
    labels: 
      app: "shop"
  spec: 
    ports: 
      - 
        port: 8080
        targetPort: 8080
    selector: 
      app: "shop"
---
  apiVersion: "apps/v1"
  kind: "Deployment"
  metadata: 
    name: "deliveryfood"
    labels: 
      app: "deliveryfood"
  spec: 
    selector: 
      matchLabels: 
        app: "deliveryfood"
    replicas: 1
    template: 
      metadata: 
        labels: 
          app: "deliveryfood"
      spec: 
        containers: 
          - 
            name: "deliveryfood"
            image: "deliveryfood"
            ports: 
              - 
                containerPort: 8080
            readinessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 10
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 10
            livenessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 120
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 5
---
  apiVersion: "v1"
  kind: "Service"
  metadata: 
    name: "deliveryfood"
    labels: 
      app: "deliveryfood"
  spec: 
    ports: 
      - 
        port: 8080
        targetPort: 8080
    selector: 
      app: "deliveryfood"
---
  apiVersion: "apps/v1"
  kind: "Deployment"
  metadata: 
    name: "customer"
    labels: 
      app: "customer"
  spec: 
    selector: 
      matchLabels: 
        app: "customer"
    replicas: 1
    template: 
      metadata: 
        labels: 
          app: "customer"
      spec: 
        containers: 
          - 
            name: "customer"
            image: "customer"
            ports: 
              - 
                containerPort: 8080
            readinessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 10
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 10
            livenessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 120
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 5
---
  apiVersion: "v1"
  kind: "Service"
  metadata: 
    name: "customer"
    labels: 
      app: "customer"
  spec: 
    ports: 
      - 
        port: 8080
        targetPort: 8080
    selector: 
      app: "customer"
